### ISSUE TITLE
Page Router

### ISSUE THREAD

**Issue by 1zunull** [enbock/Time-Tracker#15]
The router config seems at moment not really pratically.

I have follow idea:

* We could write the Root-Node code, as example `<Settings.... />` into a special template file `*.html.tpl`.
* Then is it possible to configure the route in a json:
```
{
  settings: {
    url: '/settings',
    root: '/Templates/Settings/root.html.tpl'
  }
}
```

**Comment by enbock** [comment]
Router is not back and working.
We using now "Hot Module Loading" to switch between the pages.

Config is currently placed in the Application config are (final place may comes later;)
https://github.com/enbock/Time-Tracker/blob/develop/src/Application/Application.tsx#L49
